#!/bin/bash
echo "Starting {{ APPNAME }}"

# export the variables in .golive.rc
for key_val in $(cat $HOME/.golive.rc); do
   if [[ $key_val != "export" ]]; then
      export $key_val
   fi
done

{% block exports %}{% endblock %}

exec {{ PRE_EXECUTABLE }} {{ PYTHON }} {{ PROJECT_DIR }}/manage.py run_gunicorn --settings={{ SETTINGS }} --bind=$GOLIVE_HOST:{{ PORT }} --access-logfile={{ LOGDIR }}/gunicorn_access.log --error-logfile={{ LOGDIR }}/gunicorn_error.log
