#!/bin/bash
echo "Starting {{ APPNAME }}"

# export the variables in .golive.rc
for key_val in $(cat $HOME/.golive.rc); do
   if [[ $key_val != "export" ]]; then
      export $key_val
   fi
done

exec {{ PYTHON }} {{ PROJECT_DIR }}/manage.py runfcgi --settings={{SETTINGS}} daemonize=false host=% HOST % port={{ PORT }} outlog=/home/{{USER}}/log/django.log errlog=/home/{{USER}}/log/django_error.log maxrequests=10000 maxspare=3
